In [3]:
import numpy as np
import matplotlib as m


In [4]:
X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)

y=y/100 #normlaize the outputs to be in range 0,1


#the sigmoid function converts any real-valued number into a value between 0 and 1
def sigmoid(x):
    return 1/(1+np.exp(-x))

#This derivative(derivative of sigmoid) is used during the backpropagation step in training a neural network.
def derivatives_sigmoid(x):
    return x*(1-x)


epoch=7000  # Number of training iterations
lr=0.1    # Learning rate

inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))   # Weights for input to hidden layer

#Biases are additional parameters in a neural network that allow the activation function to be shifted to the left or right

bh=np.random.uniform(size=(1,hiddenlayer_neurons))    # Biases for hidden layer
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))  # Weights for hidden to output layer
bout=np.random.uniform(size=(1,output_neurons))  # Biases for output layer


In [5]:
for i in range(epoch):
    # Forward propagation
    
    hinp1 = np.dot(X, wh)  # Calculate input to hidden layer
    hinp = hinp1 + bh  # Add bias to hidden layer input
    hlayer_act = sigmoid(hinp)  # Activation function for hidden layer

    outinp1 = np.dot(hlayer_act, wout)  # Calculate input to output layer
    outinp = outinp1 + bout  # Add bias to output layer input
    output = sigmoid(outinp)  # Activation function for output layer

    # Backpropagation
    
    EO = y - output  # Calculate output error
    outgrad = derivatives_sigmoid(output)  # Gradient of output
    d_output = EO * outgrad  # Error term for output layer

    EH = d_output.dot(wout.T)  # Error propagated to hidden layer , wout.t is transpose
    hiddengrad = derivatives_sigmoid(hlayer_act)  # Gradient of hidden layer activations
    d_hiddenlayer = EH * hiddengrad  # Error term for hidden layer

    # Update weights and biases
    
    wout += hlayer_act.T.dot(d_output) * lr  # Update weights from hidden to output layer
    wh += X.T.dot(d_hiddenlayer) * lr  # Update weights from input to hidden layer

    
    
print("Input:\n"+str(X))
print("Actual Output:\n"+str(y))
print("Predicted Output:\n",output)

Input:
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.89038397]
 [0.88936184]
 [0.89021221]]
